# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: ./mvnw clean verify

    - name: Sonar Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

    - name: Check Sonar Status
      run: |
        status=$(curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=java-repeat_java-repeat)
        echo $status | jq '.'
        status=$(echo $status | jq '.projectStatus.status')
        test '"OK"' = $status

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        JAVA_HOME: /usr/java/openjdk-15